mysql:
  url: ""
  login: ""
  password: ""

command_usage_cooldown: 40

messages:
  command_cooldown: "<red>Подождите еще <cooldown> с.!"
  invalid_executor: "<red>Неверный исполнитель!"
  database_error: "<red>Ошибка базы! Свяжитесь с администратором!"
  aura_command: "<light_purple>У вас <dark_purple><aura></dark_purple> ауры!"
  not_in_whitelist: "<red>Вас нет в белом списке!\n<light_purple>Посетите <aqua><click:open_url:\"https://aura.aniby.net\">aura.aniby.net</click></aqua>"