mysql:
  url: ''
  login: ''
  password: ''

command_usage_cooldown: 40

messages:
  command_cooldown: "<red>Подождите еще <cooldown> с. перед использованием команды!"
  not_in_whitelist: "<red>Вас нет в белом списке!"
  invalid_executor: "<red>Неверный исполнитель!"
  database_error: "<red>Ошибка базы! Свяжитесь с администратором!"
  aura_command: "<dark_purple>У вас <light_purple><aura> ауры"