name: GameMaster
version: '${project.version}'
main: net.aniby.aura.gamemaster.GameMaster
api-version: '1.20'
load: STARTUP
authors: [ An1by ]
description: Utils for Game Master and events
website: https://aura.aniby.net
softdepend:
  - GlowAPI